name: Version Increase Workflow

on:
  push:
    branches:
      - master

jobs:
  version_increase:
    runs-on: ubuntu-latest

    steps:
      - name: Check for version change
        id: version_check
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q "package.json"; then
            echo "Version in package.json file has changed."
            echo "::set-output name=version_changed::true"
          else
            echo "Version in package.json file has not changed."
            echo "::set-output name=version_changed::false"
          fi

      - name: Run on version increase
        if: steps.version_check.outputs.version_changed == 'true'
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
